server:
  port: 8884
spring:
  application:
    name: service-fegin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false