server:
  port: 8881

spring:
  application:
    name: service-app
  cloud:
    consul:
      host: 192.168.235.32
      port: 8500
      enabled: true
      discovery:
        hostname: 192.168.150.208
        port: ${server.port}
        enabled: true
        service-name: service-app
        instance-id: service-app1
        health-check-url: http://192.168.150.208:${server.port}/health
        health-check-interval: 10s