server:
  port: 8881
spring:
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: server1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8882/eureka/,http://127.0.0.1:8883/eureka/