server:
  port: 8883

spring:
  application:
    name: config-client
  rabbitmq:
    host: 192.168.235.32
    port: 5672
    username: admin
    password: 123456
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/