server:
  port: 8882

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
    stream:
      kafka:
        binder:
          zk-nodes: 192.178.235.32:2181
          brokers: 192.178.235.32:9092
    bus:
      trace:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/